sonar.projectKey=sasunmadhuranga
sonar.organization=Sasun Madhuranga

sonar.projectName=DevSecOps Pipeline
sonar.projectVersion=1.0

# Source
sonar.sources=app
sonar.language=py
sonar.python.version=3.11

# Exclusions — don't scan test fixtures or generated files
sonar.exclusions=**/__pycache__/**,**/*.pyc,terraform/**

# Coverage report (add pytest-cov later to populate this)
# sonar.python.coverage.reportPaths=coverage.xml
